# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4b2dbae28d737e734e68c198d86e9d17d88013a455c87ead244a3b88327651448d578641031b5f7a5f3a33def05b2afddca0646afb2e67a1b92a72f27877e9e

test:
  secret_key_base: 1c73167c468652dbbeaa4633f497c4305384cb068c5a4b7399ebef75296661cf6f414084dd4a8ecec5e070903bd8bc5826cc4848b7f97913f0ec261e03875493

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
